#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

wmake -s libso stressAccumulationFunctionObject

runApplication blockMesh
runApplication simpleFoam

# No longer needed to run the stressAccumulation utility as the
# stressAccumulation function object is used instead
#runApplication stressAccumulation
