#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

wclean applications/utilities/stressAccumulation

(cd pitzDaily && ./Allclean)

#------------------------------------------------------------------------------
